# build stage
FROM golang:1.24.1-alpine3.20 AS builder
WORKDIR /app
COPY . .
COPY /etc/secrets/.env .env
ENV GIN_MODE release
RUN go build -o main ./cmd/*.go

# run stage
FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/main .
COPY start.sh .

EXPOSE 8080
CMD ["/app/main"]
ENTRYPOINT ["/app/start.sh"]